"""Format-parity contract for the merged ``generate_output`` tool.

Each golden below was captured by invoking the corresponding pre-merge tool
(``generate_python_function`` / ``generate_latex_derivation`` /
``generate_derivation_report`` / ``generate_sympy_script``) on the same inputs,
then asserted byte-for-byte against the new ``format`` dispatch. This locks the
merge to pure output parity: same inputs in, identical artifact out.
"""

from __future__ import annotations

from typing import Any

from symkit_mcp.tools import codegen

# MockMCP is provided by conftest.py
# ruff: noqa: F821  # MockMCP from conftest.py

PYTHON_CASE: dict[str, Any] = {
    "name": "tension",
    "description": "Calculate tension",
    "parameters": [
        {"name": "M1", "type": "float", "description": "Mass 1"},
        {"name": "M2", "type": "float", "description": "Mass 2"},
    ],
    "steps": [{"description": "Total mass", "expression": "M1 + M2", "result_var": "M_total"}],
    "return_vars": ["M_total"],
}
GOLDEN_PYTHON: dict[str, Any] = {'success': True, 'code': 'def tension(M1: float, M2: float):\n    """Calculate tension\n\n    Args:\n        M1: Mass 1\n        M2: Mass 2\n\n    Returns:\n        dict with keys: [\'M_total\']\n\n    Note:\n        Generated by SymKit - computations use SymPy for correctness.\n    """\n    import sympy as sp\n    from sympy import sqrt, sin, cos, tan, pi, exp, log\n\n    # Step 1: Total mass\n    M_total = M1 + M2\n\n    return {"M_total": M_total}\n', 'function_name': 'tension', 'parameters': ['M1', 'M2'], 'returns': ['M_total']}

LATEX_CASE: dict[str, Any] = {
    "title": "Kinematics",
    "steps": [{"description": "Define velocity", "latex": "v = \\frac{dx}{dt}"}],
    "final_result": "x(t) = x_0 + v t",
}
GOLDEN_LATEX: dict[str, Any] = {'success': True, 'latex': '\\section{Kinematics}\n\n\\begin{align}\n    &\\text{Define velocity} \\nonumber \\\\\n    &v = \\frac{dx}{dt} \\\\\n\\end{align}\n\n\\textbf{Final Result:} $x(t) = x_0 + v t$', 'title': 'Kinematics', 'steps_count': 1}

REPORT_CASE: dict[str, Any] = {
    "problem": "terminal velocity",
    "given": {"m": "mass (kg)", "rho": "1.225 kg/m^3"},
    "steps": [{"description": "solve the balance equation",
               "latex": "v = \\sqrt{\\frac{2mg}{\\rho C_d A}}"}],
    "results": {"v_t": "sqrt(2*m*g/(rho*C_d*A))"},
    "verification": {"total": 4, "verified": 4, "failed": 0, "inconclusive": 0,
                     "note": "all steps verified"},
}
GOLDEN_REPORT: dict[str, Any] = {'success': True, 'report': '# Derivation Report\n\n## Problem\nterminal velocity\n\n## Given\n\n- $m$ = mass (kg)\n- $\\rho$ = 1.225 kg/m^3\n\n## Derivation Steps\n\n### Step 1: solve the balance equation\n$$v = \\sqrt{\\frac{2mg}{\\rho C_d A}}$$\n\n## Results\n\n- $v_t = \\sqrt{2} \\sqrt{\\frac{g m}{A C_{d} \\rho}}$\n\n## Verification\n\n- 4/4 steps verified\n- failed: 0\n- inconclusive: 0\n- all steps verified\n\n---\n*Generated by SymKit - Where Neural Meets Symbolic*', 'format': 'markdown'}

SYMPY_CASE: dict[str, Any] = {
    "expressions": [{"name": "omega", "expr": "sqrt(k/m)", "description": "angular frequency"}],
    "operations": [{"op": "solve", "input": "m*x**2 - k", "for": "x"},
                   {"op": "diff", "input": "omega", "var": "k"}],
}
GOLDEN_SYMPY: dict[str, Any] = {'success': True, 'script': '"""\nAuto-generated SymPy script by SymKit\nRun with: python script.py\n"""\n\nimport sympy as sp\nfrom sympy import symbols, sqrt, sin, cos, tan, pi, exp, log, Eq, solve, diff, integrate, simplify\n\n# Define symbols\nk, m, omega, x = symbols(\'k m omega x\')\n\n# Define expressions\n# angular frequency\nomega = sqrt(k/m)\n\n# Operations\n# Operation 1: solve\nresult_1 = solve(m*x**2 - k, x)\nprint(f\'Result 1: {result_1}\')\n\n# Operation 2: diff\nresult_2 = diff(omega, k)\nprint(f\'Result 2: {result_2}\')\n', 'language': 'python', 'requires': ['sympy']}


def _generate_output():
    mcp = MockMCP()
    codegen.register_codegen_tools(mcp)
    assert set(mcp.tools) == {"generate_output"}, sorted(mcp.tools)
    return mcp.tools["generate_output"]


def test_python_format_matches_old_generate_python_function(fresh_manager):
    _ = fresh_manager
    assert _generate_output()(format="python", **PYTHON_CASE) == GOLDEN_PYTHON


def test_latex_format_matches_old_generate_latex_derivation(fresh_manager):
    _ = fresh_manager
    assert _generate_output()(format="latex", **LATEX_CASE) == GOLDEN_LATEX


def test_markdown_report_format_matches_old_generate_derivation_report(fresh_manager):
    _ = fresh_manager
    assert _generate_output()(format="markdown_report", **REPORT_CASE) == GOLDEN_REPORT


def test_sympy_script_format_matches_old_generate_sympy_script(fresh_manager):
    _ = fresh_manager
    assert _generate_output()(format="sympy_script", **SYMPY_CASE) == GOLDEN_SYMPY
