"""
Code Generation Tools

Tools for generating executable Python code and reports from derivation steps.

These tools assemble already-verified expressions into executable form; they
perform no new calculations. Verify the derivation first with the ``math``
tool (``session=true``) plus ``session_verify_step`` / ``session_verify_session``,
then generate code or a report from the verified steps.
"""

import re
from typing import Any

# Symbols that must not be re-declared as free symbols in a generated script.
_SYMPY_RESERVED = (
    "sin", "cos", "tan", "sqrt", "exp", "log", "pi",
    "Derivative", "Integral", "oo",
)

# Required parameters per output format. Everything else is optional.
_REQUIRED: dict[str, tuple[str, ...]] = {
    "python": ("name", "description", "parameters", "steps", "return_vars"),
    "latex": ("title", "steps", "final_result"),
    "markdown_report": ("problem", "given", "steps", "results"),
    "sympy_script": ("expressions", "operations"),
}


def _to_latex(expr_str: str) -> str:
    """Render a result expression as LaTeX, falling back to the raw string.

    Result values arrive as SymPy source text (``sqrt(2)*...``); rendering
    them verbatim inside ``$...$`` is not valid LaTeX (black-box finding).
    """
    try:
        import sympy as sp

        from symkit.domain.expression_parser import build_reserved_local_dict

        # ``sympify`` folds ``E``/``I`` into exp(1)/1j; protect the user-variable
        # names the unified parser reserves (r19 F20) so ``E`` renders as ``E``.
        protected = build_reserved_local_dict(expr_str)
        expr = sp.sympify(expr_str, locals=protected) if protected else sp.sympify(expr_str)
        return str(sp.latex(expr))
    except Exception:
        return expr_str.replace("**", "^")


def _symbol_to_latex(sym: str) -> str:
    """Render a bare symbol key (Given/Results sections) as LaTeX.

    ``rho`` must become ``$\\rho$`` and ``C_d`` ``$C_{d}$``; keys that are
    not plain identifiers (units, prose) pass through unchanged.
    """
    import re as _re

    if not _re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", sym):
        return sym
    try:
        import sympy as sp

        return str(sp.latex(sp.Symbol(sym)))
    except Exception:
        return sym


def _render_python(
    name: str,
    description: str,
    parameters: list[dict[str, str]],
    steps: list[dict[str, str]],
    return_vars: list[str],
) -> dict[str, Any]:
    """Assemble a runnable Python function from verified derivation steps."""
    param_str = ", ".join(f"{p['name']}: {p.get('type', 'float')}" for p in parameters)
    doc_lines = [f'    """{description}', "", "    Args:"]
    for p in parameters:
        doc_lines.append(f"        {p['name']}: {p.get('description', '')}")
    doc_lines.extend([
        "", "    Returns:", f"        dict with keys: {return_vars}", "",
        "    Note:", "        Generated by SymKit - computations use SymPy for correctness.",
        '    """',
    ])
    step_lines = [
        "    import sympy as sp",
        "    from sympy import sqrt, sin, cos, tan, pi, exp, log",
        "",
    ]
    for i, step in enumerate(steps, 1):
        step_lines.append(f"    # Step {i}: {step['description']}")
        step_lines.append(f"    {step['result_var']} = {step['expression']}")
        step_lines.append("")
    return_dict = ", ".join(f'"{v}": {v}' for v in return_vars)
    step_lines.append(f"    return {{{return_dict}}}")
    docstring = "\n".join(doc_lines)
    code = f"""def {name}({param_str}):
{docstring}
{chr(10).join(step_lines)}
"""
    return {
        "success": True,
        "code": code,
        "function_name": name,
        "parameters": [p["name"] for p in parameters],
        "returns": return_vars,
    }


def _render_latex(title: str, steps: list[dict[str, str]], final_result: str) -> dict[str, Any]:
    """Assemble a LaTeX document from derivation steps."""
    lines = [f"\\section{{{title}}}", "", "\\begin{align}"]
    for i, step in enumerate(steps, 1):
        desc = step.get("description", f"Step {i}")
        latex = step.get("latex", step.get("expression", ""))
        lines.append(f"    &\\text{{{desc}}} \\nonumber \\\\")
        lines.append(f"    &{latex} \\\\")
    lines.extend(["\\end{align}", "", f"\\textbf{{Final Result:}} ${final_result}$"])
    return {"success": True, "latex": "\n".join(lines), "title": title, "steps_count": len(steps)}


def _given_lines(given: dict[str, str]) -> list[str]:
    return [f"- {_math_or_plain(sym)} = {val}" for sym, val in given.items()]


def _is_identifier(sym: str) -> bool:
    """Whether a key is a plain ASCII identifier renderable as a math symbol."""
    return bool(re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", sym))


def _math_or_plain(sym: str) -> str:
    """``$latex$`` for identifier keys, the raw text for anything else.

    Chinese or prose keys (field 26e9028b) are not math-mode content; wrapping
    them in ``$...$`` produced pseudo-LaTeX like ``$连续方程$``.
    """
    return f"${_symbol_to_latex(sym)}$" if _is_identifier(sym) else sym


def _step_block_lines(steps: list[dict[str, str]]) -> list[str]:
    """Render the Derivation Steps section body (no section heading)."""
    lines: list[str] = []
    for i, step in enumerate(steps, 1):
        number = step.get("number") or step.get("step") or i
        lines.append(f"### Step {number}: {step.get('description', '')}")
        if "latex" in step:
            lines.append(f"$${step['latex']}$$")
        elif "expression" in step:
            lines.append(f"$${step['expression']}$$")
        if "result" in step:
            lines.append(f"**Result:** ${step.get('result_var', '')} = {step['result']}$")
        lines.append("")
    return lines


# Keys each renderer indexes directly. A missing one used to escape as a bare
# ``KeyError`` ("Error executing tool generate_output: 'result_var'"), which
# told the caller nothing about what to fix.
_REQUIRED_ITEM_KEYS: dict[str, dict[str, tuple[str, ...]]] = {
    "python": {
        "steps": ("description", "expression", "result_var"),
        "parameters": ("name",),
    },
    "sympy_script": {
        "expressions": ("name", "expr"),
        "operations": ("op", "input"),
    },
}


def _describe_missing_item_keys(format: str, values: dict[str, Any]) -> str | None:
    """Report the first list item missing a key its renderer needs."""
    for field, keys in _REQUIRED_ITEM_KEYS.get(format, {}).items():
        for index, item in enumerate(values.get(field) or [], 1):
            if not isinstance(item, dict):
                return f"format {format!r}: {field} item {index} must be an object"
            absent = [key for key in keys if key not in item]
            if absent:
                return (
                    f"format {format!r}: {field} item {index} is missing "
                    f"{', '.join(absent)}; each item needs: {', '.join(keys)}"
                )
    return None


def _is_count(value: Any) -> bool:
    """True for a genuine int count (``bool`` is a subclass of ``int``)."""
    return isinstance(value, int) and not isinstance(value, bool)


def _count_triple_lines(verification: dict[str, int | str | bool]) -> list[str]:
    """Render the verified/total line plus failed/inconclusive counts."""
    total = verification.get("total")
    verified = verification.get("verified")
    if _is_count(total) and _is_count(verified):
        # Render the full count triple (including zeros) so readers
        # never have to infer a missing count as "zero".
        return [f"- {verified}/{total} steps verified"] + [
            f"- {key}: {verification[key]}"
            for key in ("failed", "inconclusive")
            if _is_count(verification.get(key))
        ]
    return [
        f"- {key}: {verification[key]}"
        for key in ("verified", "failed", "inconclusive")
        if _is_count(verification.get(key))
    ]


def _flag_lines(verification: dict[str, int | str | bool]) -> list[str]:
    """Render legacy boolean flags and the free-text note."""
    lines = [
        f"- {key}: {'✅' if val else '❌'}"
        for key, val in verification.items()
        if isinstance(val, bool)
    ]
    note = verification.get("note")
    if isinstance(note, str) and note:
        lines.append(f"- {note}")
    return lines


def _verification_lines(verification: dict[str, int | str | bool]) -> list[str]:
    """Render the Verification section, including its leading blank line."""
    return ["", "## Verification", ""] + _count_triple_lines(verification) + _flag_lines(verification)


def _render_report(
    problem: str,
    given: dict[str, str],
    steps: list[dict[str, str]],
    results: dict[str, str],
    verification: dict[str, int | str | bool] | None,
) -> dict[str, Any]:
    """Assemble a complete derivation report in Markdown."""
    lines = ["# Derivation Report", "", "## Problem", problem, "", "## Given", ""]
    lines.extend(_given_lines(given))
    lines.extend(["", "## Derivation Steps", ""])
    lines.extend(_step_block_lines(steps))
    lines.extend(["## Results", ""])
    for sym, expr in results.items():
        if _is_identifier(sym):
            lines.append(f"- ${sym} = {_to_latex(expr)}$")
        else:
            lines.append(f"- {sym} = ${_to_latex(expr)}$")
    if verification:
        lines.extend(_verification_lines(verification))
    lines.extend(["", "---", "*Generated by SymKit - Where Neural Meets Symbolic*"])
    return {"success": True, "report": "\n".join(lines), "format": "markdown"}


def _script_symbols(expressions: list[dict[str, str]], operations: list[dict[str, Any]]) -> list[str]:
    """Collect free symbols from expressions and operations, sorted.

    Operations routinely introduce symbols absent from the expressions
    (e.g. a solve input); declaring only the expression symbols made the
    generated script die with NameError on its first run (run-018).
    """
    words = re.compile(r"\b([a-zA-Z_][a-zA-Z0-9_]*)\b")
    found: set[str] = set()
    for expr in expressions:
        found.update(w for w in words.findall(str(expr.get("expr", ""))) if w not in _SYMPY_RESERVED)
    for op in operations:
        for field in ("input", "for", "var"):
            value = op.get(field)
            if isinstance(value, str):
                found.update(w for w in words.findall(value) if w not in _SYMPY_RESERVED)
    return sorted(found)


def _operation_lines(op: dict[str, Any], i: int) -> list[str]:
    """Render one operation of a generated SymPy script."""
    out = [f"# Operation {i}: {op['op']}"]
    if op["op"] == "solve":
        # Wrap in Eq only when the input actually contains '='; a
        # single-argument Eq() is deprecated (run-018).
        if "=" in str(op["input"]):
            lhs, _, rhs = str(op["input"]).partition("=")
            out.append(f"result_{i} = solve(Eq({lhs.strip()}, {rhs.strip()}), {op['for']})")
        else:
            out.append(f"result_{i} = solve({op['input']}, {op['for']})")
    elif op["op"] == "simplify":
        out.append(f"result_{i} = simplify({op['input']})")
    elif op["op"] == "diff":
        out.append(f"result_{i} = diff({op['input']}, {op.get('var', 'x')})")
    elif op["op"] == "integrate":
        out.append(f"result_{i} = integrate({op['input']}, {op.get('var', 'x')})")
    out.append(f"print(f'Result {i}: {{result_{i}}}')")
    out.append("")
    return out


def _render_sympy_script(
    expressions: list[dict[str, str]], operations: list[dict[str, Any]]
) -> dict[str, Any]:
    """Assemble a standalone, runnable SymPy script."""
    lines = [
        '"""',
        "Auto-generated SymPy script by SymKit",
        "Run with: python script.py",
        '"""',
        "",
        "import sympy as sp",
        "from sympy import symbols, sqrt, sin, cos, tan, pi, exp, log, Eq, solve, diff, integrate, simplify",
        "",
        "# Define symbols",
    ]
    symbols = _script_symbols(expressions, operations)
    if symbols:
        lines.append(f"{', '.join(symbols)} = symbols('{' '.join(symbols)}')")
    lines.extend(["", "# Define expressions"])
    for expr in expressions:
        lines.append(f"# {expr.get('description', '')}")
        lines.append(f"{expr['name']} = {expr['expr']}")
        lines.append("")
    lines.append("# Operations")
    for i, op in enumerate(operations, 1):
        lines.extend(_operation_lines(op, i))
    return {
        "success": True,
        "script": "\n".join(lines),
        "language": "python",
        "requires": ["sympy"],
    }


def _build_output(format: str, values: dict[str, Any]) -> dict[str, Any]:
    """Dispatch a validated ``generate_output`` call to its renderer."""
    if format == "python":
        return _render_python(values["name"], values["description"],
                              values["parameters"], values["steps"], values["return_vars"])
    if format == "latex":
        return _render_latex(values["title"], values["steps"], values["final_result"])
    if format == "markdown_report":
        return _render_report(values["problem"], values["given"], values["steps"],
                              values["results"], values["verification"])
    return _render_sympy_script(values["expressions"], values["operations"])


def register_codegen_tools(mcp: Any) -> None:
    """Register the code/report generation tool."""

    @mcp.tool(meta={"category": "Output"})
    def generate_output(
        format: str,
        name: str | None = None,
        description: str | None = None,
        parameters: list[dict[str, str]] | None = None,
        steps: list[dict[str, str]] | None = None,
        return_vars: list[str] | None = None,
        title: str | None = None,
        final_result: str | None = None,
        problem: str | None = None,
        given: dict[str, str] | None = None,
        results: dict[str, str] | None = None,
        verification: dict[str, int | str | bool] | None = None,
        expressions: list[dict[str, str]] | None = None,
        operations: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """Generate a derivation artifact in one of four formats.

        Assembles already-verified expressions into an artifact; performs no
        new calculations. Verify steps first with ``math`` (session=true) plus
        ``session_verify_step`` / ``session_verify_session``.

        Args:
            format: One of "markdown_report", "latex", "python", or
                "sympy_script". Required parameters per format:
                - markdown_report: problem, given, steps, results
                  (verification optional; each ``steps`` item may carry a
                  ``number`` (or ``step``) key rendered as the step number
                  instead of the sequential position)
                - latex: title, steps, final_result
                - python: name, description, parameters, steps, return_vars
                  (each ``parameters`` item needs name; each ``steps`` item
                  needs description, expression, result_var)
                - sympy_script: expressions, operations
                  (each ``expressions`` item needs name, expr; each
                  ``operations`` item needs op, input)
            Other parameters apply only to the formats listed above.

        Returns:
            Success dict with the artifact under ``report`` / ``latex`` /
            ``code`` / ``script``; otherwise ``success`` false plus ``error``.
        """
        values: dict[str, Any] = {
            "name": name, "description": description, "parameters": parameters,
            "steps": steps, "return_vars": return_vars, "title": title,
            "final_result": final_result, "problem": problem, "given": given,
            "results": results, "verification": verification,
            "expressions": expressions, "operations": operations,
        }
        if format not in _REQUIRED:
            return {"success": False,
                    "error": f"unknown format {format!r}; valid formats: {', '.join(_REQUIRED)}"}
        missing = [key for key in _REQUIRED[format] if values[key] is None]
        if missing:
            return {"success": False,
                    "error": f"format {format!r} requires: {', '.join(missing)}"}
        shape_error = _describe_missing_item_keys(format, values)
        if shape_error:
            return {"success": False, "error": shape_error}
        return _build_output(format, values)
